package com.digikent.vadirest.dao;

import com.digikent.vadirest.dto.*;
import com.documentum.thirdparty.javassist.bytecode.annotation.StringMemberValue;

import java.util.List;


public interface ManagementDAO {
	
	public List<BankaDurumu> getBankStatus(long id, long year);
	public List<BankaDurumuDetay> getBankStatusDetail(long id, long accountId, long year, String startDate, String endDate);
	public List<PersonelBilgileri> getStaffInfomation();
	public List<PersonelBilgileri> getPersonelKadroInformation();
	public List<PersonelBilgileriDetay> getStaffDetail(long servisGorevId, char turu);
	public List<PersonelBilgileriDetay> getKadroDetay(long servisKadroId);
	public List<PersonelGrup> getStaffGroup();
	public List<PersonelBilgileriDetay> getJobStarters(String startDate, String endDate);;
	public List<PersonelBilgileriDetay> getJobQuitters(String startDate, String endDate);;
	public List<KurumBorc> getDebtStatus(long id, long year);
	public List<YapilanOdemeler> getPayments(String startDate, String endDate);
	public List<FirmaOdeme> getAllPayments(long year, String startDate, String endDate, long personelId);
	public List<Basvuru> getApplyCount(String startDate, String endDate);
	public List<BasvuruOzet> getApplySummary(long birimId, String startDate, String endDate);
	public BasvuruOzetDetay getApplySummaryDetail(long basvuruNo);
	public List<FirmaBorc> getFirmDebtStatus(long persid, long year);
	public String getFirmaAlacakType();
	public List<FirmaAlacak> getFirmaAlacakTypeE(long year, long personelId);
	public List<FirmaAlacak> getFirmaAlacakTypeH(long year, long personelId);
	public List<FirmaOdeme> getFirmaOdeme(long year, String startDate, String endDate);
	public List<Talep> getRequestCount(String timePeriod);
	public List<GelirGrubu> getIncomeGroup(String timePeriod);
	public List<GelirGrubuDetay> getIncomeGroupDetail(long id, String startDate, String endDate);
	public List<GelirTuru> getIncomeType(String timePeriod);
	public List<GelirTuru> getIncomeType(String startDate, String endDate);
	public List<GelirTuruDetay> getIncomeTypeDetail(long id, String startDate, String endDate);
	public List<YbsMenu> getYbsParents(String userName, Long parentID);
	public List<GraphGeneral> getTodayIncomeGroup();
	public List<GraphGeneral> getIncomeGroup(String startDate, String endDate);
	public List<GraphGeneral> getIncomeType(long gelirGrubuId, String startDate, String endDate);
	public List<GraphGeneral> getIncomeManagementPayOffice(String startDate, String endDate);
	public List<GraphGeneral> getIncomeManagementPayment(String startDate, String endDate);
	public List<GraphGeneral> getIncomeManagementNotification(long year);
	public List<GraphGeneral> getIncomeManagementNotificationDetail(long id, long year);
	public List<GraphGeneral> getIncomeManagementStreetTahakkuk(long year);
	public List<GelirlerYonetimiMahalle> getIncomeManagementStreetDetail(long id, String startDate, String endDate);
	public List<GraphGeneral> getIncomeManagementStreetBorc(long year);
	public List<GraphGeneral> getIncomeManagementTaxPayer(String startDate, String endDate);
	public List<FinansmanYonetimiGelirGider> getFinancialManagementIncomeExpense();
	public List<FinansmanYonetimiGelirGider> getFinancialManagementIncome(long year, long personelId);
	public List<FinansmanYonetimiGelirGider> getFinancialManagementExpense(long year, long personelId);
	public List<FinansmanYonetimiGelirGiderAylik> getFinancialManagementIncomeExpenseMonthly(long year);
	public List<FinansmanYonetimiGelirGiderAylik> getFinancialManagementIncomeExpenseDaily(long year, long month);
	public List<FinansmanYonetimiGelirGider> getFinancialManagementIncomeBudget();
	public List<FinansmanYonetimiGelirGider> getFinancialManagementExpenseBudget();
	public List<FinansmanYonetimiTahakkuk> getFinancialManagementTahakkukFirstLevel(long year);
	public List<FinansmanYonetimiTahakkuk> getFinancialManagementTahakkukOtherLevels(String kod, int level);
	public List<GraphGeneral> getRealEstateManagement();
	public List<GraphGeneral> getRealEstateManagementDetail(long id);
	public List<GraphGeneral> getWeddingManagement();
	public List<GraphGeneral> getWeddingManagementMonthly(long year);
	public List<GraphGeneral> getWeddingManagementDaily(long year, long month);
	public List<YbsWeddingList> getWeddingManagementDailyList(long year, long month, long day);
	public List<GraphGeneral> getHealthManagement();
	public List<GraphGeneral> getHealthManagementMonthly(long year);
	public List<GraphGeneral> getHealthManagementDaily(long year, long month);
	public List<InsanKaynaklari> getHumanResourcesType();
	public List<InsanKaynaklari> getHumanResourcesTypeMudurluk(String type);
	public List<InsanKaynaklari> getHumanResourcesGender();
	public List<InsanKaynaklari> getHumanResourcesGenderMudurluk(String gender);
	public List<InsanKaynaklari> getHumanResourcesJob();
	public List<InsanKaynaklari> getHumanResourcesAge();
	public List<ToplantiYonetimi> getMeetingManagement();
	public List<ToplantiYonetimi> getMeetingManagementMonthly(long year);
	public List<BelgeYonetim> getDocumentManagement(String startDate, String endDate);
	public List<BelgeYonetim> getDocumentManagementMudurluk(String startDate, String endDate, String tur);
	public List<GraphGeneral> getLicenseCount();
	public List<GraphGeneral> getLicenseTypeCount(long year);
	public List<GraphGeneral> getLicenseTypeMonthlyCount(long year, long id);
	public List<GraphGeneral> getLicenseTypeDailyCount(long year, long month, long id);
	public List<YbsLicenseList> getLicenseTypeDailyList(long year, long month, long day, long id);
	public List<YbsGununOzeti> getDailySummary();
	public List<VezneTahsilat> getPayOfficeCollection(long persid, String startDate, String endDate);
	public List<VezneTahsilatDetay> getPayOfficeCollectionDetail(long id, String startDate, String endDate);
	public List<VezneTahsilat> getLocationCollection(long persid, String startDate, String endDate);
	public List<GununOzeti> getDailySummaryIncomeManagementTahakkuk(String requestDate);
	public List<GununOzeti> getDailySummaryIncomeManagementTahsilat(String requestDate);
	public List<GununOzeti> getDailySummaryIncomeManagementEmlakBeyani(String requestDate);
	public List<GununOzeti> getDailySummaryIncomeManagementCevreBeyani(String requestDate);
	public List<GununOzeti> getDailySummaryIncomeManagementReklamBeyani(String requestDate);
	public List<GununOzeti> getDailySummaryFinancialManagementBanka(String requestDate);
	public List<GununOzeti> getDailySummaryFinancialManagementFirmaBorcu(String requestDate);
	public List<GununOzeti> getDailySummaryFinancialManagementVergiBorcu(String requestDate);
	public List<GununOzeti> getDailySummaryFinancialManagementSosyalGuvenlikBorcu(String requestDate);
	public List<GununOzeti> getDailySummaryFinancialManagementToplamBorc(String requestDate);
	public List<GununOzeti> getDailySummaryDocumentManagementEvrak(String requestDate);
	public List<GununOzeti> getDailySummaryDocumentManagementDilekce(String requestDate);
	public List<GununOzeti> getDailySummaryDocumentManagementSikayet(String requestDate);
	public List<PersonelBilgileri> getDailySummaryHumanResourcesCounts();
	public List<GununOzeti> getDailySummaryRealEstateManagementBina();
	public List<GununOzeti> getDailySummaryRealEstateManagementNumarataj();
	public List<GununOzeti> getDailySummaryRealEstateManagementBagimsizBolum();
	public List<GununOzeti> getDailySummaryLicenseManagementRuhsatBasvurusu(String requestDate);
	public List<GununOzeti> getDailySummaryLicenseManagementVerilenRuhsat(String requestDate);
	public List<GununOzeti> getDailySummaryServiceManagementNikah(String requestDate);
	public List<GelirlerYonetimiTahakkuk> getIncomeManagementTahakkukDetail(String startDate, String endDate);
	public List<GelirlerYonetimiEmlakBeyani> getIncomeManagementEmlakBeyani(String startDate, String endDate);
	public List<GelirlerYonetimiCevreBeyani> getIncomeManagementCevreBeyani(String startDate, String endDate);
	public List<GelirlerYonetimiReklamBeyani> getIncomeManagementReklamBeyani(String startDate, String endDate);
	
}
